name: cureasap_driver
description: "CureAsap Driver - Emergency Response Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Connectivity & Maps (Citizen App ke match ka rakha hai)
  supabase_flutter: ^2.8.1
  flutter_polyline_points: ^3.1.0 # ✅ Version updated taaki tracking screen crash na ho
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.1

  # State & Logic
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  timer_count_down: ^2.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- LOGO GENERATOR PACKAGE ---
  flutter_launcher_icons: ^0.13.1

# --- LOGO CONFIGURATION ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png" # 👈 Driver wala naya logo yahan rakho
  adaptive_icon_background: "#FF3B3B"
  adaptive_icon_foreground: "assets/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png